FROM node:24-alpine3.21 as build


WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .
RUN npm run build

#for production
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off;"]